config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "application#index"

  get 'admin', to: 'admin#index'
  resources :video_games, path: 'admin/games'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/video_game.rb
# frozen_string_literal: true

# VideoGame model
class VideoGame < ApplicationRecord
  validates :title, presence: true, length: { minimum: 4, message: 'must be at least 4 characters long' }
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    redirect_to '/admin/games'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application main Controller
class ApplicationController < ActionController::Base
  def index
    @video_games = VideoGame.all
  end
end

app/controllers/video_games_controller.rb
class VideoGamesController < ApplicationController
  def index
    @video_games = VideoGame.all
  end

  def show
    @video_game = VideoGame.find(params[:id])
  end

  def new
    @video_game = VideoGame.new
  end

  def create
    @video_game = VideoGame.new(video_game_params)

    if @video_game.save
      redirect_to video_games_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @video_game = VideoGame.find(params[:id])
  end

  def update
    @video_game = VideoGame.find(params[:id])

    if @video_game.update(video_game_params)
      redirect_to video_games_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @video_game = VideoGame.find(params[:id])
    @video_game.destroy

    redirect_to video_games_path
  end

  private

  def video_game_params
    params.require(:video_game).permit(:title, :genre)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/video_games_helper.rb
module VideoGamesHelper
end

app/views/application/index.html.haml
.container.center
  %h2 What is your VARIETY gamer score ?
  .center
    %p
      Which of these Video Games series did you play
      (at least 1 game of)? 1 point per box checked!
  .left
    %p#score 0/100

.container
  - @video_games.each_slice(25) do |games|
    .row
      - games.each do |game|
        .col
          %label
            %input{ type: 'checkbox', name: 'video_games[]', value: game.id }
              %strong
                = game.title
:javascript
  document.addEventListener('change', function(event) {
    var checkboxes = document.querySelectorAll
      ('input[type="checkbox"]:checked');
    var count = checkboxes.length;
    document.getElementById('score').innerText = count + '/100';
  });

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type' }
    %title TestProject
    %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_importmap_tags
  %body
    = yield

app/views/video_games/_form.html.haml
- if video_game.errors.any?
  %h2
    = pluralize(video_game.errors.count, 'error')
    prohibited this video_game from being saved:
  %ul

= form_for video_game do |f|
  = f.label :title
  = f.text_field :title
  - video_game.errors.full_messages_for(:title).each do |message|
    %li
      = message

  = f.label :genre
  = f.text_field :genre
  - video_game.errors.full_messages_for(:genre).each do |message|
    %li
      = message

  = f.submit

app/views/video_games/edit.html.haml
= link_to 'Back', video_games_path
%br
%br
= render 'form', video_game: @video_game

app/views/video_games/index.html.haml
%h1 Admin#index

= link_to 'New Video Game', new_video_game_path

%table
  %thead
    %tr
      %th Name
      %th Genre
      %th Actions
  %tbody
    - @video_games.each do |video_game|
      %tr
        %td= link_to video_game.title, video_game_path(video_game)
        %td= video_game.genre
        %td
          = link_to 'Edit', edit_video_game_path(video_game)
          = link_to 'Destroy', video_game_path(video_game),
                    data: { turbo_method: :delete,
                            turbo_confirm: 'Are you sure?' }

app/views/video_games/new.html.haml
= link_to 'Back', video_games_path
%br
%br
= render 'form', video_game: @video_game

app/views/video_games/show.html.haml
= link_to 'Back', video_games_path

%h1= @video_game.title